name: dask-community-demos
channels:
- conda-forge
dependencies:
  # Python
  - python =3.9  # Coiled isn't available for Python 3.10 yet
  # Dask and related libraries
  - dask
  - distributed
  - coiled >=0.0.74
  # Other useful libraries
  - blosc
  - bokeh
  - dask-labextension
  - dask-ml
  - fastparquet
  - geopandas
  - ipympl
  - ipython
  - ipywidgets
  - joblib
  - jupyter-black
  - jupyterlab
  - lz4
  - matplotlib
  - numpy
  - pandas
  - pyarrow
  - python-graphviz
  - python-snappy
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - xarray
  - zarr
